=  Managing Vulnerabilities with Thamos
include::_attributes.adoc[]

[#introduce-vulnerability]
== Introducing a Vulnerability

The ``game_of_life.py`` program is a simple application that shows how Thamos manages known vulnerablities in the dependencies of a project. 
To use this example application, follow the steps mentioned above relative to the installation of the Thamos CLI and to its configuration using ``.thoth.yaml``.

To introduce voluntarily a known vulnerability in the project, specify that you would like to add pillow version 8.0.0 in your requirements:

[.lines_space]
[.console-input]
[source,bash]
thamos add pillow==8.0.0

[.lines_space]
[.console-output]
[source,bash]
2022-01-12 14:20:11,248 [217578] INFO     thamos.lib: Adding 'pillow==8.0.0' to default requirements of runtime environment 'ubi8'

This version of pillow is known for introducing a vulnerability further described on the https://github.com/pypa/advisory-db[pypa/advisory-db] repository. 
Thamos can also manage user requirements for dependencies using https://pip.pypa.io/en/stable/user_guide/#constraints-files[constraints files]. 
To add pillow version 8.0.0 in your dependency requirements this way, you can simply write the package with its version into this file.

[#thamos-resolution]
== Resolving Security Issues with Thamos

To get a stack guidance based on security, run the following command:

IMPORTANT: The resolution process might take some time as the resolver explores resolution possibilities in the dependency graph (unless cached results are already available).

[.lines_space]
[.console-input]
[source,bash]
thamos advise --recommendation-type security

[.lines_space]
[.console-output]
[source,bash]
2022-01-12 14:20:53,796 [217661] INFO     thamos.lib: Successfully submitted advise analysis 'adviser-220112132053-236b5c3ed7d5cdd' to 'https://khemenu.thoth-station.ninja/api/v1'
                                                                               Application stack guidance                                                                                
                                                                                      ╷                                                                                     ╷            
  Link                                                                                │ Message                                                                             │ Type       
 ═════════════════════════════════════════════════════════════════════════════════════╪═════════════════════════════════════════════════════════════════════════════════════╪═══════════ 
  https://quay.io/repository/thoth-station/ps-cv-ocr                                  │ Consider using a computer vision predictable stack 'ps-cv-ocr' that has prepared    │ ✔️ INFO     
                                                                                      │ environment with 'pillow'                                                           │            
  https://quay.io/repository/thoth-station/ps-cv-pytorch                              │ Consider using a computer vision predictable stack 'ps-cv-pytorch' that has         │ ✔️ INFO     
                                                                                      │ prepared environment with 'pillow'                                                  │            
  https://quay.io/repository/thoth-station/ps-cv-tensorflow                           │ Consider using a computer vision predictable stack 'ps-cv-tensorflow' that has      │ ✔️ INFO     
                                                                                      │ prepared environment with 'pillow'                                                  │            
  https://quay.io/repository/thoth-station/ps-ip-ifd                                  │ Consider using a image processing predictable stack 'ps-ip-ifd' that has prepared   │ ✔️ INFO     
                                                                                      │ environment with 'pillow'                                                           │            
  https://thoth-station.ninja/search/adviser-220112132053-236b5c3ed7d5cdd/summary     │ Results can be browsed in Thoth search                                              │ ✔️ INFO     
  https://thoth-station.ninja/j/cve_timestamp                                         │ CVE database of known vulnerabilities for Python packages was updated at            │ ⚠️ WARNING  
                                                                                      │ '2021-12-20T00:00:04.615854'                                                        │            
  https://thoth-station.ninja/j/lax_version                                           │ No version range specifier for 'asyncclick' found, it is recommended to specify     │ ⚠️ WARNING  
                                                                                      │ version ranges in requirements                                                      │            
  https://thoth-station.ninja/j/lax_version                                           │ No version range specifier for 'click' found, it is recommended to specify version  │ ⚠️ WARNING  
                                                                                      │ ranges in requirements                                                              │            
  https://thoth-station.ninja/j/lax_version                                           │ No version range specifier for 'pygame' found, it is recommended to specify version │ ⚠️ WARNING  
                                                                                      │ ranges in requirements                                                              │            
  https://thoth-station.ninja/j/thoth_s2i                                             │ It is recommended to use Thoth's s2i to have recommendations specific to runtime    │ ✔️ INFO     
                                                                                      │ environment                                                                         │            
  https://thoth-station.ninja/j/rhel_ubi                                              │ Using observations for RHEL instead of UBI, RHEL is ABI compatible with UBI         │ ⚠️ WARNING  
  https://thoth-station.ninja/recommendation-types/                                   │ Using recommendation type 'security'                                                │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ Resolving for runtime environment named 'ubi8'                                      │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ Resolving for operating system 'rhel' in version '8'                                │ -          
  https://thoth-station.ninja/j/env                                                   │ Resolving for Python version '3.8'                                                  │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ Using platform 'linux-x86_64'                                                       │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ No constraints supplied to the resolution process                                   │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ Using supplied static source code analysis                                          │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ No containerized environment used                                                   │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ Using CPU family 'UNKNWON' model 'UNKNOWN'                                          │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ No CUDA used                                                                        │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ No cuDNN used                                                                       │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ No OpenBLAS used                                                                    │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ No OpenMPI used                                                                     │ ✔️ INFO     
  https://thoth-station.ninja/j/env                                                   │ No MKL used                                                                         │ ✔️ INFO     
  https://thoth-station.ninja/j/eol_env                                               │ Runtime environment used is no longer supported, it is recommended to switch to     │ ⚠️ WARNING  
                                                                                      │ another runtime environment                                                         │            
  https://thoth-station.ninja/j/prescription                                          │ Using prescriptions 'thoth' release 'v0.13.0'                                       │ ✔️ INFO     
  https://github.com/thoth-station/prescriptions                                      │ Using resolver prescriptions from thoth-station/prescriptions                       │ ✔️ INFO     
  https://thoth-station.ninja/j/no_cpu                                                │ No CPU model provided, please state CPU model in your .thoth.yaml configuration     │ ⚠️ WARNING  
                                                                                      │ file to have recommendations optimized for your runtime environment                 │            
  https://thoth-station.ninja/j/no_cpu                                                │ No CPU family provided, please state CPU family in your .thoth.yaml configuration   │ ⚠️ WARNING  
                                                                                      │ file to have recommendations optimized for your runtime environment                 │            
  https://thoth-station.ninja/j/rules                                                 │ Removing package 'click' in versions '<=6.6' from index 'https://pypi.org/simple'   │ ⚠️ WARNING  
                                                                                      │ based on rule: Package released before December 2016                                │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve- │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
  2021-25288-fix-oob-read-in-jpeg2kdecode                                             │ 'PYSEC-2021-137' was found                                                          │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve- │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
  2021-25288-fix-oob-read-in-jpeg2kdecode                                             │ 'PYSEC-2021-138' was found                                                          │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28675-fix- │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
  dos-in-psdimageplugin                                                               │ 'PYSEC-2021-139' was found                                                          │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-317' was found                                                          │            
  https://pillow.readthedocs.io/en/stable/releasenotes/index.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-331' was found                                                          │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-35' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-36' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-37' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-38' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-39' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-40' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-41' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-42' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/index.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-69' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/index.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-70' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/index.html                     │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-71' was found                                                           │            
  https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix- │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
  fli-dos                                                                             │ 'PYSEC-2021-92' was found                                                           │            
  https://github.com/python-pillow/Pillow/pull/5377                                   │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-93' was found                                                           │            
  https://github.com/python-pillow/Pillow/pull/5377                                   │ Skipping including package ('pillow', '8.0.0', 'https://pypi.org/simple') as a CVE  │ ⚠️ WARNING  
                                                                                      │ 'PYSEC-2021-94' was found                                                           │            
  https://thoth-station.ninja/j/unresolved                                            │ Cannot satisfy direct dependencies: direct dependencies of type 'pillow' were       │ ❌ ERROR   
                                                                                      │ removed by pipeline sieves                                                          │            
  https://thoth-station.ninja/j/install_error                                         │ The following versions of 'asyncclick' from                                         │ ⚠️ WARNING  
                                                                                      │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were  │            
                                                                                      │ removed due to installation issues in the target environment: 7.0.3                 │            
  https://thoth-station.ninja/j/install_error                                         │ The following versions of 'click' from                                              │ ⚠️ WARNING  
                                                                                      │ 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple' were  │            
                                                                                      │ removed due to installation issues in the target environment: 8.0.2                 │            
                                                                                      ╵                                                                                     ╵            
                                        Cannot satisfy direct dependencies: direct dependencies of type 'pillow' were removed by pipeline sieves 

Or modify the recommendation_type field to security in ``.thoth.yaml`` to set it as your default recommendation type, and simply run:

[.lines_space]
[.console-input]
[source,bash]
thamos advise

Thamos report should show that an error occurred during the resolution process because a known vulnerability was found in pillow version 8.0.0. Thoth checks vulnerabilities of direct dependencies, but also possible vulnerabilities in indirect dependencies (also known as transitive dependencies of the application). The resolution process respects https://thoth-station.ninja/docs/developers/adviser/experimental_features.html#strict-index-configuration[Python package index configuration] to avoid possible https://developers.redhat.com/articles/2021/12/21/prevent-python-dependency-confusion-attacks-thoth#dependency_management_in_python[dependency confusion attacks].

[#run-application]
== Running the Example Application

Now that you know how Thamos prevents the use of unsafe dependencies in your application, you can revert to another version of pillow to complete this part of the tutorial. 
To launch the example application with the resolved dependencies, run:

[.lines_space]
[.console-input]
[source,bash]
thamos run --no-pedantic ./game_of_life.py

To launch a new game with the default parameters or choose your own parameters as specified in the help section. Click on the coordinates to select your first generation of individuals and press p to see next generations.

++++
<script>
document.getElementsByClassName("doc")[0].style.maxWidth = "100%";
</script>
++++
