=  Container Image Security with Thoth
include::_attributes.adoc[]

[#image-guidance]
== Container Image Security Guidance

Thoth can also provide security guidance for container images available for your application with the command:

[.lines_space]
[.console-input]
[source,bash]
thamos images

Each entry stated in the output can be set as a base_image in :.thoth.yaml: in the respective https://thoth-station.ninja/docs/developers/thamos/#overlays-directory[runtime environment section] and used as a base for running the Python applications.

Project Thoth offers container https://developers.redhat.com/articles/2021/11/25/build-and-extend-containerized-applications-project-thoth#thoth_and_python_packaging_standards[image analyses] that introspect what is present in the container image. Notably, it can extract:

* Information about the operating system
* Information about RPM packages that are present in the container image
* Python packages that are present in the container image and their locations, if multiple virtual environments are available
* Python interpreters and their available versions
* Information about the ABI provided
* Container image metadata as extracted by https://github.com/containers/skopeo[Skopeo]
* Information about other libraries, such as the CUDA version (GPU software) available

All these data can give you insights on the software that is available for use.

Thoth's resolver can consider the results of container image analyses listed earlier, along with available hardware and requirements for your application. This way, the resolution process can come up with https://thoth-station.ninja/docs/developers/adviser/introduction.html[the best possible software for the given application].

You can find more detail about Thoth's security recommendations for containers and other Thoth functionalities in the following articles:

* https://developers.redhat.com/articles/2021/11/17/customize-python-dependency-resolution-machine-learning[Customize Python dependency resolution with machine learning]
* https://developers.redhat.com/articles/2021/11/25/build-and-extend-containerized-applications-project-thoth[Build and extend containerized applications with Project Thoth]
* https://developers.redhat.com/articles/2021/09/29/secure-your-python-applications-thoth-recommendations[Secure your Python applications with Thoth recommendations]
* https://developers.redhat.com/articles/2021/12/21/prevent-python-dependency-confusion-attacks-thoth[Prevent Python dependency confusion attacks with Thoth]
* https://developers.redhat.com/articles/2021/09/22/thoth-prescriptions-resolving-python-dependencies[Thoth prescriptions for resolving Python dependencies]

++++
<script>
document.getElementsByClassName("doc")[0].style.maxWidth = "100%";
</script>
++++
